name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Determine tag name
        id: tag_name
        run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"
      - name: Login to Dockerhub registry
        uses: docker/login-action@v3
        with:
          username: scaletechio
          password: ${{ secrets.DOCKERHUB }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "scaletechio/copernicusmarine:${{ steps.tag_name.outputs.tag_name }}"
