name: Docker Image CI

on:
  push:
    branches:
      - "master"
      - "main"
      - "development"
      - "test"
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Determine tag or branch
      id: tag_or_branch
      run: echo "::set-output name=tag_or_branch::$(echo ${GITHUB_REF#refs/*/})"
    - name: Determine tag or branch name
      id: tag_or_branch_name
      run: echo "::set-output name=tag_or_branch_name::$(if [[ '${{ steps.tag_or_branch.outputs.tag_or_branch }}' == 'tags' ]]; then echo ${GITHUB_REF#refs/tags/}; else echo ${GITHUB_REF#refs/heads/}; fi)"
    - name: Login to Dockerhub registry
      uses: docker/login-action@v3
      with:
        username: scaletechio
        password: ${{ secrets.DOCKERHUB }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: |
            scaletechio/copernicusmarine:${{ steps.tag_or_branch_name.outputs.tag_or_branch_name }}
