name: Docker Image CI

on:
  push:
    branches: [ "master", "main", "development", "test" ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Login to Dockerhub registry
      uses: docker/login-action@v3
      with:
        username: scaletechio
        password: ${{ secrets.DOCKERHUB }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: |
            scaletechio/copernicusmarine:${{ steps.extract_branch.outputs.branch }}
            scaletechio/copernicusmarine:${{ github.ref }}
